feat: [OeX_Cred-206] add program certificates list endpoint
raccoongang/credentials pull request #12
Opened 2023-01-28 21:11 UTC by Thposbsmt

**Run JavaScript tests locally with Karma**

There is work being done on a fix to get Karma to run in CI. Until then, however, contributors are required to run these tests locally.

- [ ] Make sure you are inside the devstack container
- [ ] Run `make test-karma`
- [ ] All tests pass

2023-01-31 19:05 UTC, wowkalucky requested changes
Please, see items.

2023-01-31 19:05 UTC, wowkalucky commented on credentials/apps/verifiable_credentials/rest_api/v1/serializers.py
> +class ProgramCredentialSerializer(serializers.Serializer):  # pylint: disable=abstract-method
Seems, we use this serializer for validation only?
If so, making it readonly should increase productivity.

2023-02-01 07:51 UTC, Thposbsmt commented on credentials/apps/verifiable_credentials/rest_api/v1/views.py
> +    authentication_classes = (
In defaults it's `credentials.apps.api.authentication.JwtAuthentication`, we use `from edx_rest_framework_extensions.auth.jwt.authentication import JwtAuthentication`

2023-02-01 11:40 UTC, wowkalucky approved these changes
Well done!

2023-02-01 11:41 UTC, merged