feat: [OeX_Cred-778] update Open Badges v3 verifiable credential composition
raccoongang/credentials pull request #47
Opened 2023-06-18 17:43 UTC by wowkalucky

**Run JavaScript tests locally with Karma**

There is work being done on a fix to get Karma to run in CI. Until then, however, contributors are required to run these tests locally.

- [ ] Make sure you are inside the devstack container
- [ ] Run `make test-karma`
- [ ] All tests pass

2023-06-19 19:08 UTC, GlugovGrGlib requested changes
Looks good, the only part that should be changed is with the credentials description template and unused function

2023-06-19 19:08 UTC, GlugovGrGlib commented on credentials/apps/verifiable_credentials/composition/open_badges.py
> +    NOTE: for example purposes, for now.
Maybe we should be more specific for community, e.g., like this:

```suggestion
    Open Badges version 3.0.1 data model.

    NOTE: this is example of extending data model with custom fields and overrides.
```

2023-06-20 10:44 UTC, wowkalucky commented on credentials/apps/verifiable_credentials/issuance/models.py
> +            "{credential_type} is granted on program {program_title} completion offered by {organizations}, in collaboration with {platform_name}. The {program_title} program includes {course_count}
> Square brackets possibly should be used for the optionality 😸 
No problem.

2023-06-20 17:34 UTC, GlugovGrGlib approved these changes
LGTM!

2023-06-20 17:36 UTC, merged